remote_theme: jakartaee/jekyll-theme-jakarta-ee

title: [tck_faces_v4_0]
description: [Oracle Technology Compatibility Kit User's Guide for Jakarta Faces 4.0 for Technology Licensees, Release 4.0]

# sidebar links url
links:
  source: https://github.com/jakartaee/faces
  download: https://github.com/jakartaee/faces/releases
  #mailinglist: https://javaee.groups.io/g/tck_jaxrs_v2_1
  #javadocs:
  docs: https://github.com/jakartaee/faces
  #faq:

